### ISSUE TITLE
MagnificPopup breaking Portfolio image hyperlinks

### ISSUE THREAD

**Issue by tyarosevich** [StartBootstrap/startbootstrap-creative#226]
Presumably, one would want portfolio images to link to outside resources instead of a bigger image in the code here from `src/pug/index.pug` : 
```
div#portfolio
            .container-fluid.p-0
                .row.no-gutters
                    .col-lg-4.col-sm-6
                        a.portfolio-box(href='assets/img/portfolio/fullsize/1.jpg')
                            img.img-fluid(src='assets/img/portfolio/thumbnails/1.jpg', alt='')
                            .portfolio-box-caption
                                .project-category.text-white-50
                                    | Category
                                .project-name
                                    | Project Name
```

If one tries to change the href in a.portfolio-box() to, e.g. an outside website, it will not work. The culprit is the MagnificPopup libarary call. I don't know anything about query.js but I was able to make the link work by commenting out this code in `src/js/scripts.js`:  
```
    // Magnific popup calls
    $('#portfolio').magnificPopup({
        delegate: 'a',
        type: 'image',
        tLoading: 'Loading image #%curr%...',
        mainClass: 'mfp-img-mobile',
        gallery: {
            enabled: true,
            navigateByImgClick: true,
            preload: [0, 1]
        },
        image: {
            tError: '<a href="%url%">The image #%curr%</a> could not be loaded.'
        }
    });
```

**Comment by davidtmiller** [comment]
Hi there,

I tried this out using images brought in via external links and it works just fine. Commenting out the entire initialization script for this would cause the gallery simply to link out to an external image in a new window. This code within the portfolio item worked as intended:

```
a.portfolio-box(href='https://source.unsplash.com/WLUHO9A_xik/1600x900')
    img.img-fluid(src='https://source.unsplash.com/WLUHO9A_xik/600x400', alt='...')
        .portfolio-box-caption
            .project-category.text-white-50
                | Category
            .project-name
                | Project Name
```

Make sure your URL and path are correct if using images that aren't local to the project. I will consider getting these images hosted somewhere externally to bring down the download package size, but the plugin doesn't seem to have any issues. I will be looking for an alternative to this plugin however moving into the Bootstrap 5 version of the theme since jQuery will be dropped.
